export const COUNTRY_CODES = [
  { code: "+977", country: "np", name: "Nepal" },
  { code: "+91", country: "in", name: "India" },
  { code: "+1", country: "us", name: "USA/Canada" },
  { code: "+44", country: "gb", name: "UK" },
  { code: "+61", country: "au", name: "Australia" },
  { code: "+81", country: "jp", name: "Japan" },
  { code: "+86", country: "cn", name: "China" },
  { code: "+971", country: "ae", name: "UAE" },
  { code: "+974", country: "qa", name: "Qatar" },
  { code: "+966", country: "sa", name: "Saudi Arabia" },
  { code: "+65", country: "sg", name: "Singapore" },
  { code: "+60", country: "my", name: "Malaysia" },
  { code: "+66", country: "th", name: "Thailand" },
  { code: "+92", country: "pk", name: "Pakistan" },
  { code: "+880", country: "bd", name: "Bangladesh" },
  { code: "+94", country: "lk", name: "Sri Lanka" },
  { code: "+975", country: "bt", name: "Bhutan" },
  { code: "+960", country: "mv", name: "Maldives" },
];
